Repository codinasion/program, pull requests merged in 2022-11, with the labels that each got.

#3498 Code to print reverse of a number using GoLang
  program/print-reverse-of-a-number/print_reverse_of_a_number.go
Labels: triage

#4800 Added convert Time from 24 hour format to 12 hour format
  program/convert-time-from-24-hour-to-12-hour-format/ConvertTimeFrom24-hourTo12-hourFormat.cpp
Labels: triage

#4753 Create `find-the-maximum-sum-of-a-contiguous-subarray-(kadane's-algorithm).py`
  program/find-the-maximum-sum-of-a-contiguous-subarray-(kadane's-algorithm)/find-the-maximum-sum-of-a-contiguous-subarray-(kadane's-algorithm).py
Labels: triage

#4689 Create `find-surface-area-of-a-cone.py`
  program/find-surface-area-of-a-cone/find-surface-area-of-a-cone.py
Labels: triage

#4587 Create `linear-search.py`
  dsa/linear-search/linear-search.py
Labels: triage

#4425 Create `convert-a-string-to-an-integer.py`
  program/convert-a-string-to-an-integer/convert_a_string_to_an_integer.py
Labels: triage

#4236 Create `convert-kilometers-to-miles.py`
  program/convert-kilometers-to-miles/convert-kilometers-to-miles.py
Labels: triage

#4165 Create `convert-miles-to-meters.py`
  program/convert-miles-to-meters/convert-miles-to-meters.py
Labels: triage

#4135 Create `print-pattern-1.py`
  program/print-pattern-1/print-pattern-1.py
Labels: triage

#2956 Create `find-largest-number-in-an-array.py`
  program/find-largest-number-in-an-array/find-largest-number-in-an-array.py
Labels: Python

#4779 feat(matrices): C++ program for matrices addition
  program/add-two-matrices/AddTwoMatrices.cpp
Labels: C++

#4757 create ConvertHoursToMinutes program in kotlin#4646
  program/convert-hours-to-minutes/ConvertHoursToMinutes.kt
Labels: triage

#4772 Create PrintNumbersFromNTo1WithoutUsingALoop kotlin program#4438
  program/print-numbers-from-n-to-1-without-using-a-loop/PrintNumbersFromNTo1WithoutUsingALoop.kt
Labels: triage

#3465 done with this program in fs
  program/find-volume-of-a-cube/FindVolumeOfCube.fs
Labels: triage

#2954 Java program to find largest number in an array
  program/find-largest-number-in-an-array/FindLargestNumberInAnArray.java
Labels: triage

#2953 Check Digit Java Program Added
  program/check-digit/CheckDigit.java
Labels: triage

#2921 added C program for finding sum of n natural numbers by recursion
  program/find-sum-of-n-natural-numbers-by-recursion/FindSumOfNNaturalNumbersByRecursion.c
Labels: triage

#2922 convert hours to days using c++
  program/convert-hours-to-days/ConvertHoursToDays.cpp
Labels: triage

#2925 [ 🚧 WIP ] print number to words using js
  program/print-number-to-words/PrintNumberToWords.js
Labels: JavaScript

#4009 Create ConvertTimeFrom12-hourTo24-hourFormat.ts
  program/convert-time-from-12-hour-to-24-hour-format/ConvertTimeFrom12-hourTo24-hourFormat.ts
Labels: triage

#3963 Implement convert decimal to hexadecimal number.
  program/convert-decimal-to-hexadecimal/ConvertDecimalToHexadecimal.ts
Labels: triage

#3869 [ 🚧 WIP ] Added JS Program to Convert Decimal to Binary (#3855)
  program/convert-decimal-to-binary/ConvertDecimalToBinary.js
Labels: triage

#3868 [ 🚧 WIP ] Add C Program to Convert Decimal to Binary (#3847)
  program/convert-decimal-to-binary/ConvertDecimalToBinary.c
Labels: triage

#3839 ConvertCentimetersToInches.java
  program/convert-centimeters-to-inches/ConvertCentimetersToInches.java
Labels: triage

#3833 ConvertSecondsToHours.java
  program/convert-seconds-to-hours/ConvertSecondsToHours.java
Labels: triage

#3832 FindMinimumOfNNumbers.java
  program/find-minimum-of-n-numbers/FindMinimumOfNNumbers.java
Labels: triage

#3807 Add TypeScript program to convert miles to meters
  program/convert-miles-to-meters/ConvertMilesToMeters.ts
Labels: triage

#3803 add JavaScript program to convert seconds to hours
  program/convert-seconds-to-hours/ConvertSecondsToHours.js
Labels: triage

#3802 Create ConvertStringToCamelcase.c
  program/convert-string-to-camelcase/ConvertStringToCamelcase.c
Labels: triage

#3779 Create FindMinimumOfNNumbers.kt
  program/find-minimum-of-n-numbers/FindMinimumOfNNumbers.kt
Labels: triage

#3778 add TypeScript program to check valid date
  program/check-valid-date/CheckValidDate.ts
Labels: triage

#3777 added area of cube in java
  program/find-area-of-a-cube/FindAreaOfACube.java
Labels: triage

#3772 Create ConvertSecondsToHours.c
  program/convert-seconds-to-hours/ConvertSecondsToHours.c
Labels: triage

#3720 Write a C++ program to find perimeter of a square
  program/find-perimeter-of-a-square/FindPerimeterOfASquare.cpp
Labels: triage

#3692 Done testing and logic for convert from minutes to hours in Golang
  program/convert-minutes-to-hours/convert_minutes_to_hours.go
Labels: triage

#3669 Create ConvertSecondsToDays.js
  program/convert-seconds-to-days/ConvertSecondsToDays.js
Labels: triage

#3641 Added Convert Minutes to Hours in JavaScript
  program/convert-minutes-to-hours/ConvertMinutesToHours.js
Labels: triage

#3615 Added code to find the square root.
  program/find-square-root-of-a-number/find_square_root_of_a_number.go
Labels: triage

#3613 Add Find Area of A Cube
  program/find-area-of-a-cube/FindAreaOfACube.kt
Labels: triage

#3584 Create DetermintOfMatrix.c
  program/find-determinant-of-a-matrix/DetermintOfMatrix.c
Labels: triage

#3581 Create SecondLargestNumberInArray.go
  program/find-second-largest-number-in-an-array/SecondLargestNumberInArray.go
Labels: triage

#4797 [ 🚧 WIP ] ConvertMinutesToHours.js
  program/convert-minutes-to-hours/ConvertMinutesToHours.js
Labels: JavaScript

#4787 print-diamond-pattern
  program/print-diamond-pattern/print-diamond-pattern.dart
Labels: triage

#3085 Create linear_search.go
  dsa/linear-search/linear_search.go
Labels: triage

#4798 ConvertMinutesToDays.js
  program/convert-minutes-to-days/ConvertMinutesToDays.js
Labels: triage

#4771 create FindSurfaceAreaOfACuboid in kotlin#4464
  program/find-surface-area-of-a-cuboid/FindSurfaceAreaOfACuboid.kt
Labels: triage

#4770 Create FindSecondSmallestNumberInAnArray kotlin program#4487
  program/find-smallest-number-in-an-array/FindSecondSmallestNumberInAnArray.kt
Labels: triage

#4768 Create CheckIntegerOrFloat kotlin program#4532
  program/check-integer-or-float/CheckIntegerOrFloat.kt
Labels: triage

#4767 create FindSurfaceAreaOfACone kotlin program#4577
  program/find-surface-area-of-a-cone/FindSurfaceAreaOfACone.kt
Labels: triage

#4769 Create ConvertHoursToMinutes C# program #4637
  program/convert-hours-to-minutes/ConvertHoursToMinutes.cs
Labels: triage

#4792 Create convert_a_string_to_an_integer.go
  program/convert-a-string-to-an-integer/convert_a_string_to_an_integer.go
Labels: triage

#4107 closes #4060
  program/swap-two-numbers-without-using-third-variable/swap-two-numbers-without-using-third-variable.java
Labels: triage

#4790 :construction: feat: added Java# solution to convert decimal to hexadecimal
  program/convert-decimal-to-hexadecimal/ConversationDecTohex.java
Labels: triage

#4786 Create FindPerimeterOfASquare.java #4247
  program/find-perimeter-of-a-square/FindPerimeterOfASquare.java
Labels: triage

#4791 Create FindCubeRootOfANumber.java #4223
  program/find-cube-root-of-a-number/FindCubeRootOfANumber.java
Labels: triage

#4802 Create ConvertOctalToBinary.js #4508
  program/convert-octal-to-binary/ConvertOctalToBinary.js
Labels: triage

#4731 :sparkles: add ConvertStringToPascalcase/java
  program/convert-string-to-pascalcase/ConvertStringToPascalcase.java
Labels: triage

#4159 Print Pattern 1 File added #4113
  program/print-pattern-1/PrintPattern1.cpp
Labels: triage

#4110 Create ConvertStringToPascalcase.js #4094
  program/convert-string-to-pascalcase/ConvertStringToPascalcase.js
Labels: triage

#4260 add function to convert days to seconds
  program/convert-days-to-seconds/convert_days_to_seconds.dart
Labels: triage

#4307 Ruby/convert minutes to seconds
  program/convert-minutes-to-seconds/ConvertMinutesToSeconds.rb
Labels: triage

#4312 Create FindCubeRootOfANumber.ts
  program/find-cube-root-of-a-number/FindCubeRootOfANumber.ts
Labels: triage

#4355 Create ConvertDaysToHours.ts
  program/convert-days-to-hours/ConvertDaysToHours.ts
Labels: triage

#4357 Create PrintAsciiValueOfACharacter.ts
  program/print-ascii-value-of-a-character/PrintAsciiValueOfACharacter.ts
Labels: triage

#4358 Create PrintAsciiValueOfACharacter.js
  program/print-ascii-value-of-a-character/PrintAsciiValueOfACharacter.js
Labels: triage

#4359 Create CheckLowerCase.js
  program/check-lower-case/CheckLowerCase.js
Labels: triage

#4424 Added ap sum c++
  program/find-sum-of-ap-series/findSumOfAp.cpp
Labels: triage

#4474 Create PrintNumbersFromNTo1WithoutUsingALoop.ts (#4447)
  program/print-numbers-from-n-to-1-without-using-a-loop/PrintNumbersFromNTo1WithoutUsingALoop.js
  program/print-numbers-from-n-to-1-without-using-a-loop/PrintNumbersFromNTo1WithoutUsingALoop.ts
Labels: triage

#4475 added surface area of cuboid
  program/find-surface-area-of-a-cuboid/FindSurfaceAreaOfACuboid.rb
Labels: triage

#4610 create matrix_trace.php
  program/find-the-trace-of-a-matrix/find_the_trace_of_a_matrix.php
Labels: triage

#4658 c program to convert hours to minutes
  program/convert-hours-to-minutes/ConvertHoursToMinutes.c
Labels: triage

#4719 :bug: add: cpp program to `convert hrs to min` (#4638)
  program/convert-hours-to-minutes/ConvertHoursToMinutes.cpp
Labels: triage

#4662 ConvertHoursToMinutes
  program/convert-hours-to-minutes/ConvertHoursToMinutes.cpp
Labels: triage

#4588 add_two_matrix
  program/add-two-matrices/add_two_matrix.php
Labels: triage

#4498 Adding Find Perimeter Of A Square - Scala
  .gitignore
  program/find-perimeter-of-a-square/findPerimeterOfASquare.scala
Labels: triage

#4452 Added calculate permutations.... for multiple languages.
  program/calculate-the-permutation-of-n-objects-taken-r-at-a-time/CalculateThePermutationOfNObjectsTakenRAtATime.java
  program/calculate-the-permutation-of-n-objects-taken-r-at-a-time/CalculateThePermutationOfNObjectsTakenRAtATime.js
  program/calculate-the-permutation-of-n-objects-taken-r-at-a-time/CalculateThePermutationOfNObjectsTakenRAtATime.ts
  program/calculate-the-permutation-of-n-objects-taken-r-at-a-time/calculateThePermutationOfNObjectsTakenRAtATime.scala
  program/calculate-the-permutation-of-n-objects-taken-r-at-a-time/calculate_the_permutation_of_n_objects_taken_r_at_a_time.go
  program/calculate-the-permutation-of-n-objects-taken-r-at-a-time/calculate_the_permutation_of_n_objects_taken_r_at_a_time.rs
Labels: triage

#4308 Adding find perimeter of a square
  program/find-perimeter-of-a-square/FindPerimeterOfASquare.cpp
Labels: triage

#4448 GO program to check lower case
  program/check-lower-case/check_lower_case.go
Labels: triage

#4402 Resolves #4240 #4138
  program/find-perimeter-of-a-square/FindPerimeterOfASquare.c
  program/print-ascii-value-of-a-character/PrintAsciiValueOfACharacter.c
Labels: triage

#4356 ts program to check lower case
  program/check-lower-case/CheckLowerCase.ts
Labels: triage

#4263 Create FindCubeRootOfANumber.js
  program/find-cube-root-of-a-number/FindCubeRootOfANumber.js
Labels: triage

#4687 Added JavaScript code for Average of numbers by recursion
  program/find-average-of-numbers-by-recursion/avg.js
Labels: triage

#4705 Added find square root of a number method in ts
  program/find-square-root-of-a-number/FindSquareRootOfANumber.ts
Labels: triage

#4710 Completed find-the-trace-of-a-matrix in JavaScript
  program/find-the-trace-of-a-matrix/find-the-trace-of-a-matrix.js
Labels: triage

#4704 Added Diamond Pattern problem in C++
  program/print-diamond-pattern/print-diamond-pattern.c
  program/print-diamond-pattern/print-diamond-pattern.cpp
Labels: triage

#4716 Add a C++ program to find average of numbers by recursion
  program/find-average-of-numbers-by-recursion/FindAverageOfNumbersByRecursion.cpp
Labels: triage

#4193 I-3894: Convert dec to hex javascript
  program/convert-decimal-to-hexadecimal/ConvertDecimalToHexadecimal.js
Labels: triage

#4727 :sparkles: add: js program to `find area of cuboid` (#4473)
  program/find-surface-area-of-a-cuboid/FindSurfaceAreaOfACuboid.ts
Labels: triage

#4723 :truck: add: prgram in ts to `find surface area of cone` (#4586)
  program/find-surface-area-of-a-cone/FindSurfaceAreaOfACone.ts
Labels: triage

#4724 :fire: add: js program to `find surface area of cone` (#4575)
  program/find-surface-area-of-a-cone/FindSurfaceAreaOfACone.js
Labels: triage

#4264 Dart/convert minute to seconds
  program/convert-minutes-to-seconds/convert_minutes_to_seconds.dart
Labels: triage

#4725 Create `FindMinimumOfNNumbers.js`
  program/find-minimum-of-n-numbers/findMinimumOfNNumbers.js
Labels: triage

#4694 Added Kotlin file for MaximumSumSubarray
  program/find-the-maximum-sum-of-a-contiguous-subarray-(kadane's-algorithm)/FindTheMaximumSumOfAContiguousSubarray.kt
Labels: triage

#4745 Added a CheckIntegerOrFloat.cpp file in folder
  program/check-integer-or-float/CheckIntegerOrFloat.cpp
Labels: triage

#4746 Added a CheckIntegerOrFloat.c file
  program/check-integer-or-float/CheckIntegerOrFloat.c
Labels: triage

#4747 Added a ConvertOctalToBinary.c file
  program/convert-octal-to-binary/ConvertOctalToBinary.c
Labels: triage

#4748 Added a FindSecondSmallestNumberInAnArray.c file
  program/find-second-smallest-number-in-an-array/FindSecondSmallestNumberInAnArray.c
Labels: triage

#4749 Added a FindSecondSmallestNumberInAnArray.cpp file
  program/find-second-smallest-number-in-an-array/FindSecondSmallestNumberInAnArray.cpp
Labels: triage

#4751 Added a FindSurfaceAreaOfACone.c file
  program/find-surface-area-of-a-cone/FindSurfaceAreaOfACone.c
Labels: triage

#4238 feat: added PrintPattern1.ts
  package.json
  program/print-pattern-1/PrintPattern1.ts
Labels: triage

#4688 Convert hours to minutes
  program/convert-hours-to-minutes/ConvertHoursToMinutes.js
Labels: triage

#4752 Added a FindTheTraceOfAMatrix.c file
  program/find-the-trace-of-a-matrix/FindTheTraceOfAMatrix.c
Labels: triage

#4756 Added ConvertStringToPascalcase/ts
  program/convert-string-to-pascalcase/ConvertStringToPascalcase.ts
Labels: triage

#4760 Create checkleapyear.php
  program/check-leap-year/checkleapyear.php
Labels: triage

#4761 Create Check Alphabet program in C#
  program/check-alphabet/CheckAlphabet.cs
Labels: triage

#4762 Add Javascript function to check digit
  program/check-digit/check-digit.js
Labels: triage

#4763 convert string to integer js
  program/convert-a-string-to-an-integer/ConvertAStringToAnInteger.js
Labels: triage

#4782 feat(convert-hours-to-minutes): converts hours to mins haskell program
  program/convert-hours-to-minutes/convert_hours_to_minutes.hs
Labels: triage

#4732 Create print-diamond-pattern.go (codinasion#4671)
  program/print-diamond-pattern/print-diamond-pattern.go
Labels: triage

#4784 C# program for diamond pattern
  program/print-diamond-pattern/diamond_pattern.cs
Labels: triage

#4758 print-diamond-pattern
  program/print-diamond-pattern/print-diamond-pattern.dart
Labels: triage

#4785 R-Diamond -Pattern
  program/print-diamond-pattern/print_diamond_pattern.r
Labels: triage

#4775 create ConvertDaysToWeeks kotlin program#4392
  program/convert-days-to-weeks/ConvertDaysToWeeks.kt
Labels: triage

#4780 Create ConvertMinutesToDays program in kotlin#4324
  program/convert-minutes-to-days/ConvertMinutesToDays.kt
Labels: triage

#4774 create ConvertAStringToAnInteger kotlin program#4414
  program/convert-a-string-to-an-integer/ConvertAStringToAnInteger.kt
Labels: triage

#4803 Create find_surface_area_of_a_cone.go
  program/convert-a-string-to-an-integer/convert_a_string_to_an_integer.go
  program/find-surface-area-of-a-cone/find_surface_area_of_a_cone.go
Labels: triage

#4081 Create FindSmallestNumberInAnArray.c
  program/find-smallest-number-in-an-array/FindSmallestNumberInAnArray.c
Labels: triage

#3892 Added check_digit function to check if input is a digit or not a digit
  program/check-digit/CheckDigit.rb
Labels: triage

#4010 Create ConvertTimeFrom12-hourTo24-hourFormat.js
  program/convert-time-from-12-hour-to-24-hour-format/ConvertTimeFrom12-hourTo24-hourFormat.js
Labels: triage

#4033 Create PrintPascal'sTriangle.ts
  program/print-pascal's-triangle/PrintPascal'sTriangle.ts
Labels: triage

#4034 Create PrintPascal'sTriangle.js
  program/print-pascal's-triangle/PrintPascal'sTriangle.js
Labels: triage

#4082 Create PrintPascal'sTriangle.c
  program/print-pascal's-triangle/PrintPascal'sTriangle.c
Labels: triage

#4109 Create SwapTwoNumbersWithoutUsingThirdVariable.js
  program/swap-two-numbers-without-using-third-variable/SwapTwoNumbersWithoutUsingThirdVariable.js
Labels: triage

#4136 added a num pattern
  program/print-pattern-1/PrintPattern1.java
Labels: triage

#4160 Create ConvertSecondsToWeeks.js
  program/convert-seconds-to-weeks/ConvertSecondsToWeeks.js
Labels: triage

#4163 Created FindAreaOfACuboid.js
  program/find-area-of-a-cuboid/FindAreaOfACuboid.js
Labels: triage

#4164 Create ConvertMilesToMeters.js
  program/convert-miles-to-meters/ConvertMilesToMeters.js
Labels: triage

#4188 Created ConvertStringToCamelcase.ts
  program/convert-string-to-camelcase/ConvertStringToCamelcase.ts
Labels: triage

#4191 Created PrintPattern1.js
  program/print-pattern-1/PrintPattern1.js
Labels: triage

#4237 solution of permutation of n objects
  calculate-the-permutation-of-n-objects-taken-r-at-a-time.py
Labels: triage

#3843 Conversion Time 24 hours form 12 hours.
  program/Time convert 24 form 12/12_24_hour.c
  program/convert-time-from-12-hour-to-24-hour-format/ConvertTimeFrom12-hourTo24-hourFormat.c.c
  program/print-pascal's-triangle/PrintPascal'sTriangle.cpp
Labels: triage

#4804 [ 🚧 WIP ] Create FindSumOfNumbersByRecursion.js
  program/find-sum-of-numbers-by-recursion/FindSumOfNumbersByRecursion.java
Labels: Java

#4805 [ 🚧 WIP ] C program to add two matrices
  program/add-two-matrices/AddTwoMatrices.c
Labels: C

#4807 code to find area of a cube
  program/find-area-of-a-cube/find-area-of-a-cube.py
Labels: Python

#4808 Develop muriella(12h 24h)
  program/convert-time-from-12-hour-to-24-hour-format/convert_time_from_12_hour_to_24_hour_format.java
Labels: triage

#4806 [ 🚧 WIP ] Java program to find volume of a cube
  program/find-volume-of-a-cube/FindVolumeOfACube.java
Labels: Java

#4809 [ 🚧 WIP ] Transponse of a matrix in python succesfully created
  program/find-the-transpose-of-a-matrix/find-the-transpose-of-a-matrix.py
Labels: Python

#4764 feat(average of numbers by recursion in kotlin) : issue #4622
  program/find-average-of-numbers-by-recursion/FindAverageOfNumbersByRecursion.kt
Labels: triage

#4810 [ 🚧 WIP ] added convert_octal_to_binary.go file
  program/convert-octal-to-binary/convert_octal_to_binary.go
Labels: GO

#4816 Program that convert string to lowercase created in C#
  program/convert-string-to-lowercase/ConvertStringToLowercase.cs
Labels: triage

#4819 Program that conmverts centimeters to feet in Ruby created
  program/convert-centimeters-to-feet/ConvertCentimetersToFeet.rb
Labels: triage

#4817 Program that converts miles to inches in Ruby created
  program/convert-miles-to-inches/ConvertMilesToInches.rb
Labels: triage

#4813 check number data type in golang
  program/check-integer-or-float/check_integer_or_float.go
Labels: triage

#4814 Matrix transponse java
  program/find-the-transpose-of-a-matrix/FindTheTransposeOfAMatrix.java
Labels: triage

#4815 Program that convert miles to inches in java created
  program/convert-miles-to-inches/ConvertMilesToInches.java
Labels: triage

#4818 Program that find digital root of a number in Ruby created
  program/find-digital-root-of-a-number/FindDigitalRootOfANumber.rb
Labels: triage

#4812 Create print_numbers_from_n_to_1_without_using_a_loop.go
  program/convert-a-string-to-an-integer/convert_a_string_to_an_integer.go
  program/find-surface-area-of-a-cuboid/find_surface_area_of_a_cuboid.go
  program/print-numbers-from-n-to-1-without-using-a-loop/print_numbers_from_n_to_1_without_using_a_loop.go
Labels: triage

#4820 Create `add-two-matrices.py`
  program/add-two-matrices/add-two-matrices.py
Labels: triage

#4821 Create `convert-octal-to-binary.py`
  program/convert-octal-to-binary/convert-octal-to-binary.py
Labels: triage

#4822 Create `convert-days-to-weeks.py`
  program/convert-days-to-weeks/convert-days-to-weeks.py
Labels: triage
