Repository codinasion/program, pull requests merged in 2022-10, with the labels that each got.

#307 [ 🚧 WIP ] Cuboid volume
  program/find-volume-of-a-cuboid/FindVolumeOfACuboid.c
  program/find-volume-of-a-cuboid/FindVolumeOfACuboid.cpp
Labels: C, C++

#309 [ 🚧 WIP ] Hello world
  program/print-hello-world/PrintHelloWorld.c
  program/print-hello-world/PrintHelloWorld.cpp
  program/print-hello-world/PrintHelloWorld.js
  program/print-hello-world/PrintHelloWorld.kt
  program/print-hello-world/print-hello-world.py
  program/print-hello-world/print_hello_world.php
Labels: C, C++, JavaScript, Kotlin, PHP, Python

#318 [ 🚧 WIP ] Created a JS programme for DivideTwoNumbers.
  program/divide-two-numbers/DivideTwoNumbers.js
Labels: JavaScript

#323 [ 🚧 WIP ] Volumeof cube
  program/find-volume-of-a-cuboid/FindVolumeOfACuboid.java
  program/find-volume-of-cube/FindVolumeOfCube.java
  program/print-hello-world/PrintHelloWorld.java
Labels: Java

#310 [ 🚧 WIP ] Create find-volume-of-cube.go
  program/find-volume-of-cube/find_volume_of_cube.go
Labels: GO

#316 [ 🚧 WIP ] Created Find Volume Of A Cuboid
  program/find-volume-of-a-cuboid/find_volume_of_a_cuboid.go
Labels: GO

#325 [ 🚧 WIP ] Add python program to find volume of cube #76
  program/find-volume-of-cube/find-volume-of-cube.py
Labels: Python

#313 [ 🚧 WIP ] Created a GoLang file to get square of any input
  program/find-square-of-a-number/find_square_of_a_number.go
Labels: GO

#311 [ 🚧 WIP ] Created print-hello-world go file
  program/print-hello-world/print_hello_world.go
Labels: GO

#317 [ 🚧 WIP ] Created conversion of meters to miles
  program/convert-meters-to-miles/convert_meters_to_miles.go
Labels: GO

#315 [ 🚧 WIP ] Cube of a given number
  program/find-cube-of-a-number/find_cube_of_a_number.go
Labels: GO

#326 [ 🚧 WIP ] Dividetwo number
  program/divide-two-numbers/DivideTwoNumbers.java
  program/find-square-of-a-number/FindSquareOfANumber.java
Labels: Java

#320 [ 🚧 WIP ] feat: adds TS program to find cube of a number
  program/find-cube-of-a-number/FindCubeOfANumber.ts
Labels: triage, TypeScript

#312 [ 🚧 WIP ] added ts file to return the division of 2 numbers
  program/divide-two-numbers/DivideTwoNumbers.ts
Labels: TypeScript

#306 [ 🚧 WIP ] added swift file
  program/find-cube-of-a-number/FindCubeOfANumber.swift
Labels: Swift

#302 [ 🚧 WIP ] added python program divide two number
  program/divide-two-numbers/divide-two-numbers.py
Labels: Python

#327 [ 🚧 WIP ] Created two code files - One in C and other in C#
  program/convert-meters-to-miles/ConvertMetersToMiles.c
  program/find-volume-of-a-cuboid/FindVolumeOfACuboid.cs
Labels: C, C#

#329 [ 🚧 WIP ] Hello world in Typescript
  program/print-hello-world/PrintHelloWorld.ts
Labels: TypeScript

#321 Solve findVolumeOfACuboid challenge using typescript
  program/find-volume-of-a-cuboid/findVolumeOfACuboid.ts
Labels: triage

#476 Add Rust program that converts feet to miles
  program/convert-feet-to-miles/convert_feet_to_miles.rs
Labels: triage

#376 [ 🚧 WIP ] add: convert seconds to minutes in TypeScript
  program/convert-seconds-to-minutes/ConvertSecondsToMinutes.ts
Labels: TypeScript

#403 [ 🚧 WIP ] add: rust program for meter to mile
  program/convert-meters-to-miles/convert_meters_to_miles.rs
Labels: Rust

#402 [ 🚧 WIP ] wrote program to divide two numbers in golang
  program/divide-two-numbers/dvide_two_numbers.go
Labels: GO

#399 [ 🚧 WIP ] added hello world in swift language
  program/print-hello-world/PrintHelloWorld.swift
Labels: Swift

#425 [ 🚧 WIP ] Writing a R program to print hello world
  program/print-hello-world/print_hello_world.r
Labels: R

#427 [ 🚧 WIP ] Writing a C# program to print hello world
  program/print-hello-world/PrintHelloWorld.cs
Labels: C#

#505 [ 🚧 WIP ] add cube of a number program in php
  program/find-cube-of-a-number/find_cube_of_a_number.php
Labels: PHP

#480 [ 🚧 WIP ] program to convert miles to feet
  program/convert-miles-to-feet/ConvertMilesToFeet.js
  program/convert-miles-to-feet/convert-miles-to-feet.py
Labels: JavaScript, Python

#504 [ 🚧 WIP ] Python program to convert feet to miles
  program/convert-feet-to-miles/convert-feet-to-miles.py
Labels: Python

#330 [ 🚧 WIP ] CubeofNumber
  program/find-cube-of-a-number/FindCubeOfANumber.java
Labels: Java

#374 [ 🚧 WIP ] ADD: miles to feet in php
  program/convert-miles-to-feet/convert_miles_to_feet.php
Labels: PHP

#426 [ 🚧 WIP ] divide two number in R
  program/divide-two-numbers/divide_two_numbers.r
Labels: R

#428 [ 🚧 WIP ] Hello world in Rust
  program/print-hello-world/print_hello_world.rs
Labels: Rust

#430 [ 🚧 WIP ] Created a convert_feet_to_miles function in PHP.
  program/convert-feet-to-miles/convert_feet_to_miles.php
Labels: PHP

#433 [ 🚧 WIP ] Created divide_two_numbers function in PHP.
  program/divide-two-numbers/divide_two_numbers.php
Labels: PHP

#454 [ 🚧 WIP ] Created FindAreaOfASquare in JavaScript.
  program/find-area-of-a-square/FindAreaOfASquare.js
Labels: JavaScript

#404 [ 🚧 WIP ] seconds to minutes in golang
  program/convert-seconds-to-minutes/convert_seconds_to_minutes.go
Labels: GO

#529 [ 🚧 WIP ] Add program to convert miles to feet written in C
  program/convert-miles-to-feet/ConvertMilesToFeet.c
Labels: C

#530 [ 🚧 WIP ] Add program written in C++
  program/convert-miles-to-feet/ConvertMilesToFeet.cpp
Labels: C++, hacktoberfest-accepted

#551 [ 🚧 WIP ] Add program written in C
  program/convert-feet-to-miles/ConvertFeetToMiles.c
Labels: C

#328 [ 🚧 WIP ] Ruby Program - Convert Meters to Miles
  program/convert-meters-to-miles/ConvertMetersToMiles.rb
Labels: Ruby

#528 [ 🚧 WIP ] Convert Binary to Octal
  convert-binary-to-octal/convert-binary-to-octal.py
  find-sum-of-squares-of-numbers-by-recursion/find-sum-of-squares-of-numbers-by-recursion.py
Labels: Python

#552 [ 🚧 WIP ] Add program written in C++
  program/convert-feet-to-miles/ConvertFeetToMiles.cpp
Labels: C++

#431 [ 🚧 WIP ] Created convert_seconds_to_minutes in PHP.
  program/convert-seconds-to-minutes/convert_seconds_to_minutes.php
Labels: PHP

#455 [ 🚧 WIP ] Solution for Find Area of a Square in PHP.
  program/find-area-of-a-square/find_area_of_a_square.php
Labels: PHP

#507 [ 🚧 WIP ] Create octalToHexadecimal.ts
  program/convert-octal-to-hexadecimal/ConvertOctalToHexadecimal.ts
Labels: TypeScript

#575 [ 🚧 WIP ] Ruby program that calculates and returns the power of the number by recursion
  program/find-power-of-a-number-by-recursion/find_power_of_a_number_by_recursion.rb
Labels: Ruby

#577 [ 🚧 WIP ] Ruby program to return the sum of squares of numbers
  program/find-sum-of-squares-of-numbers-by-recursion/find_sum_of_squares_of_numbers_by_recursion.rb
Labels: Ruby

#506 [ 🚧 WIP ] added Java program to convert meters to miles
  program/convert-meters-to-miles/ConvertMetersToMiles.java
Labels: Java

#601 [ 🚧 WIP ] Add python program to convert seconds to minutes
  program/convert-seconds-to-minutes/convert-seconds-to-minutes.py
Labels: Python

#626 [ 🚧 WIP ] Binary to octal TS
  program/convert-binary-to-octal/ConvertBinaryToOctal.ts
Labels: TypeScript

#599 [ 🚧 WIP ] Add kotlin program to convert binary to octal
  program/convert-binary-to-octal/convert-binary-to-octal.kt
Labels: Kotlin

#625 [ 🚧 WIP ] programs for reverse-string-via-recursion
  program/print-reverse-of-a-string-by-recursion/PrintReverseOfAStringByRecursion.c
  program/print-reverse-of-a-string-by-recursion/PrintReverseOfAStringByRecursion.cpp
  program/print-reverse-of-a-string-by-recursion/PrintReverseOfAStringByRecursion.cs
  program/print-reverse-of-a-string-by-recursion/PrintReverseOfAStringByRecursion.js
  program/print-reverse-of-a-string-by-recursion/print_reverse_of_a_string_by_recursion.go
  program/print-reverse-of-a-string-by-recursion/print_reverse_of_a_string_by_recursion.php
Labels: C, C#, C++, GO, JavaScript, PHP

#670 [ 🚧 WIP ] added print ascii value of a string java
  program/print-ascii-value-of-a-string/PrintAsciiValueOfAString.java
Labels: Java

#696 [ 🚧 WIP ] ConvertoctaltoDecimal
  program/convert-octal-to-decimal/ConvertOctalToDecimal.java
Labels: Java

#698 [ 🚧 WIP ] Find maximum of n numbers c sharp
  program/find-maximum-of-n-numbers/FindMaximumOfNNumbers.cs
Labels: C#

#724 [ 🚧 WIP ] feat: add multiple programs
  program/convert-hexadecimal-to-binary/ConvertHexadecimalToBinary.ts
  program/convert-inches-to-centimeters/ConvertInchesToCentimeters.js
  program/find-maximum-of-n-numbers/FindMaximumOfNNumbers.ts
  program/print-reverse-of-a-string-by-recursion/PrintReverseOfAStringByRecursion.ts.ts
Labels: JavaScript, TypeScript

#731 [ 🚧 WIP ] Write a C program to find area of a circle
  program/find-area-of-a-circle/FindAreaOfACircle.c
Labels: C

#600 [ 🚧 WIP ] PrintAsciiValueOfAString
  program/print-ascii-value-of-a-string/PrintAsciiValueOfAString.cpp
Labels: C++

#812 [ 🚧 WIP ] Area of a circle
  program/find-area-of-a-circle/FindAreaOfACircle.java
Labels: Java

#813 [ 🚧 WIP ] Factorial using recursion
  program/find-factorial-of-a-number-by-recursion/FindFactorialOfANumberByRecursion.java
Labels: Java

#835 [ 🚧 WIP ] Sum of Digits using recursion
  program/find-sum-of-digits-of-a-number-by-recursion/FindSumOfDigitsOfANumberByRecursion.ts
Labels: TypeScript

#780 [ 🚧 WIP ] ADD: function to convert miles to feets in TS
  program/convert-miles-to-feet/ConvertMilesToFeet.ts
Labels: TypeScript

#776 [ 🚧 WIP ] ADD: function to convert octal to decimal in TS
  program/convert-octal-to-decimal/ConvertOctalToDecimal.ts
Labels: TypeScript

#725 [ 🚧 WIP ] ADD: functionality to find area of circle for JS
  program/find-area-of-a-circle/FindAreaOfACircle.js
Labels: JavaScript

#839 [ 🚧 WIP ] print-ascii-value-of-a-string python
  program/print-ascii-value-of-a-string/print-ascii-value-of-a-string.py
Labels: Python

#841 [ 🚧 WIP ] Converting paisa into rupees
  program/convert-paise-to-rupees/ConvertPaiseToRupees.java
Labels: Java

#729 [ 🚧 WIP ] add ts file to find the area of a circle
  program/find-area-of-a-circle/FindAreaOfACircle.ts
Labels: TypeScript

#843 [ 🚧 WIP ] add python file to get the lcm of 2 numbers
  program/find-lcm-of-two-numbers-by-recursion/find-lcm-of-two-numbers-by-recursion.py
Labels: Python

#849 [ 🚧 WIP ] (add): Convert Paise to Rupee in Go
  program/convert-paise-to-rupees/convert_paise_to_rupees.go
Labels: GO

#851 [ 🚧 WIP ] (add): Convert Paise to Rupee in C
  program/convert-paise-to-rupees/ConvertPaiseToRupees.c
Labels: C

#875 [ 🚧 WIP ] Added python program to convert hexadecimal to binary
  program/convert-hexadecimal-to-binary/convert-hexadecimal-to-binary.py
Labels: Python

#874 [ 🚧 WIP ] Added python program to convert octal to hexadecimal
  program/convert-octal-to-hexadecimal/convert-octal-to-hexadecimal.py
Labels: Python

#852 [ 🚧 WIP ] Added python program to find sum of digits of a number by recursion
  program/find-sum-of-digits-of-a-number-by-recursion/find-sum-of-digits-of-a-number-by-recursion.py
Labels: Python

#624 Create find-power-of-a-number-by-recursion.py
  program/find-power-of-a-number-by-recursion/find-power-of-a-number-by-recursion.py
Labels: Python

#726 [ 🚧 WIP ] ADD: function to find area of a square by side in TS
  program/find-area-of-a-square/FindAreaOfASquare.ts
Labels: TypeScript

#777 [ 🚧 WIP ] ADD Octal To Decimal in C++
  program/convert-octal-to-decimal/ConvertOctalToDecimal.cpp
Labels: C++

#781 [ 🚧 WIP ] Add TypeScript Function - Area of Right-Angled Triangle
  program/find-area-of-a-right-angled-triangle/FindAreaOfARightAngledTriangle.ts
Labels: TypeScript

#807 [ 🚧 WIP ] PHP: Implement convert inches to centimeters + tests
  program/convert-inches-to-centimeters/convert_inches_to_centimeters.php
Labels: PHP

#479 [ 🚧 WIP ] Added javascript file to convert octal to hexadecimal.
  program/convert-octal-to-hexadecimal/ConvertOctalToHexadecimal.js
Labels: JavaScript

#882 [ 🚧 WIP ] Create FindFactorialOfANumberByRecursion.kt
  program/find-factorial-of-a-number-by-recursion/FindFactorialOfANumberByRecursion.kt
Labels: Kotlin

#910 [ 🚧 WIP ] Create FindVolumeOfASphere.c
  program/find-volume-of-a-sphere/FindVolumeOfASphere.c
Labels: C

#913 [ 🚧 WIP ] Create FindSumOfDigitsOfANumberByRecursion.kt
  program/find-sum-of-digits-of-a-number-by-recursion/FindSumOfDigitsOfANumberByRecursion.kt
Labels: Kotlin

#933 [ 🚧 WIP ] Create FindSumOfSquaresOfNumbersByRecursion.kt
  program/find-sum-of-squares-of-numbers-by-recursion/FindSumOfSquaresOfNumbersByRecursion.kt
Labels: Kotlin

#934 [ 🚧 WIP ] Create FindAreaOfASquare.kt
  program/find-area-of-a-square/FindAreaOfASquare.kt
Labels: Kotlin

#935 [ 🚧 WIP ] Create PrintReverseOfAString.kt
  program/print-reverse-of-a-string/PrintReverseOfAString.kt
Labels: Kotlin

#998 [ 🚧 WIP ] Convert decimal to octal using Python
  program/convert-decimal-to-octal/convert-decimal-to-octal.py
Labels: Python

#1000 [ 🚧 WIP ] Python program to find sum of numbers
  program/find-sum-of-numbers/find-sum-of-numbers.py
Labels: Python

#836 [ 🚧 WIP ] Sum of numbers via recursion on rust
  program/find-sum-of-digits-of-a-number-by-recursion/find_sum_of_digits_of_a_number_by_recursion.rs
Labels: Rust

#838 [ 🚧 WIP ] SumOfDigitsByRecursion-C++_File
  program/find-area-of-a-right-angled-triangle/FindAreaOfARightAngledTriangle.cpp
  program/find-sum-of-digits-of-a-number-by-recursion/FindSumOfDigitsOfANumberByRecursion.cpp
Labels: C++

#1048 [ 🚧 WIP ] add Hello world in Haskell Script
  program/print-hello-world/PrintHelloWorld.hs
Labels: Haskell

#906 [ 🚧 WIP ] Create find-volume-of-a-sphere.py
  program/find-volume-of-a-sphere/find-volume-of-a-sphere.py
Labels: Python

#847 [ 🚧 WIP ] maximum of two numbers javascript func completed
  program/find-maximum-of-n-numbers/FindMaximumOfNNumbers.js
Labels: JavaScript

#1150 [ 🚧 WIP ] Add code in java to check upper case
  program/check-upper-case/CheckUpperCase.java
Labels: Java

#1151 [ 🚧 WIP ] Checking Consonants in JS
  program/check-consonant/CheckConsonant.js
Labels: JavaScript

#1173 [ 🚧 WIP ] Print character of an ASCII value in TS
  program/print-character-of-an-ascii-value/PrintCharacterOfAnAsciiValue.ts
Labels: TypeScript

#693 [ 🚧 WIP ] Hexadecimal to binary conversion in java
  program/convert-hexadecimal-to-binary/ConvertHexadecimalToBinary.java
Labels: Java

#911 [ 🚧 WIP ] Create FindVolumeOfASphere.java
  program/find-volume-of-a-sphere/FindVolumeOfASphere.java
Labels: Java

#1046 [ 🚧 WIP ] Add program in C++
  program/convert-decimal-to-octal/ConvertDecimalToOctal.cpp
  program/print-character-of-an-ascii-value/PrintCharacterOfAnAsciiValue.c
  program/print-character-of-an-ascii-value/PrintCharacterOfAnAsciiValue.cpp
Labels: C, C++, hacktoberfest-accepted

#1177 [ 🚧 WIP ] (add): Print Reverse of a String in Go
  program/print-reverse-of-a-string/print_reverse_of_a_string.go
Labels: GO

#1003 [ 🚧 WIP ] Python binary to hexadecimal convertor
  program/convert-binary-to-hexadecimal/convert-binary-to-hexadecimal.py
Labels: Python

#1178 [ 🚧 WIP ] Convert Minutes to Weeks in TS
  program/convert-minutes-to-weeks/ConvertMinutesToWeeks.ts
Labels: TypeScript

#1179 [ 🚧 WIP ] Convert Minutes to Weeks in JS
  program/convert-minutes-to-weeks/ConvertMinutesToWeeks.js
Labels: JavaScript

#1181 [ 🚧 WIP ] (add): Check Consonant in Go
  program/check-consonant/check_consonant.go
Labels: GO

#1100 [ 🚧 WIP ] added octal to hexadecimal java
  program/convert-octal-to-hexadecimal/ConvertOctalToHexadecimal.java
Labels: Java

#1202 [ 🚧 WIP ] ADD: Weeks to Minutes in C++
  program/convert-weeks-to-minutes/ConvertWeeksToMinutes.cpp
Labels: C++

#1204 [ 🚧 WIP ] Convert Hours to Seconds in TS
  program/convert-hours-to-seconds/ConvertHourstoSeconds.ts
Labels: TypeScript

#1205 [ 🚧 WIP ] ADD: Check Consonant in C++
  program/check-consonant/CheckConsonant.cpp
Labels: C++

#779 [ 🚧 WIP ] ADD: function to find lcm of two numbers by recursion in TS
  program/find-lcm-of-two-numbers-by-recursion/FindLcmOfTwoNumbersByRecursion.ts
Labels: TypeScript

#1203 [ 🚧 WIP ] Print ascii value of a string in JavaScript
  program/print-ascii-value-of-a-string/PrintAsciiValueOfAString.js
Labels: JavaScript

#671 [ 🚧 WIP ] Add a new Swift program
  program/convert-inches-to-centimeters/ConvertInchesToCentimeters.swfit
Labels: Swift

#1234 [ 🚧 WIP ] Added Convert inches to miles Dart
  program/convert-inches-to-miles/convert-inches-to-miles.py
  program/convert-inches-to-miles/convert_inches_to_miles.dart
Labels: Dart, Python

#1024 [ 🚧 WIP ] Find volume of cube in swift
  program/find-volume-of-cube/find-volume-of-cube.swift
Labels: Swift

#1283 [ 🚧 WIP ] TypeScript program to check Pangram String
  program/check-pangram-string/CheckPangramString.ts
Labels: TypeScript

#1281 [ 🚧 WIP ] typescript program to check for an armstrong number
  program/check-armstrong-number/check-armstrong-number.ts
Labels: TypeScript

#1285 [ 🚧 WIP ] Sum of numbers
  program/find-sum-of-numbers/FindSumOfNumbers.java
Labels: Java

#1302 [ 🚧 WIP ] Create ConvertInchesToMiles.ts
  program/convert-inches-to-miles/ConvertInchesToMiles.ts
Labels: TypeScript

#1307 [ 🚧 WIP ] Create ConvertInchesToMiles.js
  program/convert-inches-to-miles/ConvertInchesToMiles.js
Labels: JavaScript

#1309 [ 🚧 WIP ] Create CheckArmstrongNumber.cpp
  program/check-armstrong-number/CheckArmstrongNumber.cpp
Labels: C++

#1310 [ 🚧 WIP ] Print All PrimeNumbers Between TwoNumbers
  program/print-all-prime-numbers-between-two-numbers/PrintAllPrimeNumbersBetweenTwoNumbers.cpp
Labels: C++

#1284 [ 🚧 WIP ] Add check pangram function in Javascript
  program/check-pangram-string/CheckPangramString.js
Labels: JavaScript

#879 [ 🚧 WIP ] Sum of cube of numbers
  program/find-sum-of-cubes-of-numbers/FindSumOfCubesOfNumbers.ts
Labels: TypeScript

#903 [ 🚧 WIP ] Calculating Volume of Sphere using ts
  program/find-volume-of-a-sphere/FindVolumeOfASphere.ts
Labels: TypeScript

#1311 [ 🚧 WIP ] added kotlin code for convert_seconds_to_minutes issue #352
  program/convert-seconds-to-minutes/convert_seconds_to_minutes.kt
Labels: Kotlin

#845 [ 🚧 WIP ] Convert inches to centimeters
  program/convert-inches-to-centimeters/convert-inches-to-centimeters.py
Labels: Python

#905 [ 🚧 WIP ] Calculating Volume of Sphere in JS file
  program/find-volume-of-a-sphere/VolumeOfSphere.js
Labels: JavaScript

#1025 [ 🚧 WIP ] Write a Rust program to print the reverse of a string (#929)
  program/print-reverse-of-a-string/print_reverse_of_a_string.rs
Labels: Rust

#778 [ 🚧 WIP ] Solution of sum of digits of a number by recursion
  program/find-sum-of-digits-of-a-number-by-recursion/FindSumOfDigitsOfANumberByRecursion.java
Labels: Java

#728 [ 🚧 WIP ] ADD: function to find lcm for two nums by recursion
  program/find-lcm-of-two-numbers-by-recursion/FindLcmOfTwoNumbersByRecursion.js
Labels: JavaScript

#574 [ 🚧 WIP ] add ts file to return the power of a number by recursion
  program/find-power-of-a-number-by-recursion/FindPowerOfANumberByRecursion.ts
Labels: TypeScript

#627 [ 🚧 WIP ] add ts file for print ascii value of a string
  program/print-ascii-value-of-a-string/PrintAsciiValueOfAString.ts
Labels: TypeScript

#1077 [ 🚧 WIP ] Reverse of a string in JS
  program/print-reverse-of-a-string/reverse_string.js
Labels: JavaScript

#720 [ 🚧 WIP ] Created area of circle in GoLang
  program/find-area-of-a-circle/find_area_of_a_circle.go
Labels: GO

#997 [ 🚧 WIP ] Conversion from Decimal to Octal in TS
  program/convert-decimal-to-octal/convert_decimal_to_octal.ts
Labels: TypeScript

#999 [ 🚧 WIP ] Conversion from Decimal to Octal in JS
  program/convert-decimal-to-octal/convert_decimal_to_octal.js
Labels: JavaScript

#840 [ 🚧 WIP ] Conversion from Binary to Octal in JS
  program/convert-binary-to-octal/convert_binary_to_octal_value.js
Labels: JavaScript

#722 [ 🚧 WIP ] Created GoLang program that returns area of Square
  program/find-area-of-a-square/find_area_of_a_square.go
Labels: GO

#672 [ 🚧 WIP ] Added octal to decimal js and oct to hex cpp
  program/convert-octal-to-decimal/convert-octal-to-decimal.js
Labels: JavaScript

#1050 [ 🚧 WIP ] Solution of program to print reverse of a string using java
  program/print-reverse-of-a-string/PrintReverseOfAString.java
Labels: Java

#837 [ 🚧 WIP ] Sum of digits with recursion in JS
  program/find-sum-of-digits-of-a-number-by-recursion/sum_of_digits_with_recursion.js
Labels: JavaScript

#808 [ 🚧 WIP ] Created a factorial.ts file.
  program/find-factorial-of-a-number-by-recursion/factorial.ts
Labels: TypeScript

#1231 [ 🚧 WIP ] added js program convert feet to miles
  program/convert-feet-to-miles/ConvertFeetToMiles.js
Labels: JavaScript

#844 [ 🚧 WIP ] Conversion from Paise to Rupees in ts
  program/convert-paise-to-rupees/paise_to_rupees.ts
Labels: TypeScript

#1053 Create print_character_of_an_ascii_value.php
  program/print-character-of-an-ascii-value/print_character_of_an_ascii_value.php
Labels: triage

#1343 [ 🚧 WIP ] done with program in kotlin
  program/convert-weeks-to-minutes/ConvertWeeksToMinutes.kt
Labels: Kotlin

#1344 [ 🚧 WIP ] written program in go
  program/convert-weeks-to-minutes/convert_weeks_to_minutes.go
Labels: GO

#1052 [ 🚧 WIP ] Convert binary to hexadecimal
  program/convert-binary-to-hexadecimal/binary_to_hexadecimal.ts
Labels: TypeScript

#1070 [ 🚧 WIP ] Convert binary to hexadecimal in JS
  program/convert-binary-to-hexadecimal/binary_to_hexadecimal.js
Labels: JavaScript

#1076 [ 🚧 WIP ] Reverse a string using TS
  program/print-reverse-of-a-string/reverse_string.ts
Labels: TypeScript

#1001 [ 🚧 WIP ] Finding Sum of Numbers in TS
  program/find-sum-of-numbers/sum_of_numbers.ts
Labels: TypeScript
