Repository codinasion/program, pull requests merged in 2022-09, with the labels that each got.

#84 [ 🚧 WIP ] Solve find square of number program
  program/find-square-of-a-number/FindSquareOfANumber.ts
Labels: TypeScript

#145 [ 🚧 WIP ] volume of the cuboid
  program/find-volume-of-a-cuboid/find-volume-of-a-cuboid.py
  program/find-volume-of-a-cuboid/findVolumeOfACuboid.scala
Labels: Python, Scala

#195 [ 🚧 WIP ] Add js program to find cube of a number #133
  program/find-cube-of-a-number/FindCubeOfANumber.js
Labels: JavaScript

#297 [ 🚧 WIP ] added meters to miles function
  program/convert-meters-to-miles/ConvertMetersToMiles.ts
Labels: TypeScript

#298 [ 🚧 WIP ] Added python program to covert meters to miles
  program/convert-meters-to-miles/convert-meters-to-miles.py
Labels: Python

#300 [ 🚧 WIP ] Added python program to find cube of a number
  program/find-cube-of-a-number/find-cube-of-a-number.py
Labels: Python

#301 [ 🚧 WIP ] Adding a c++ program to find cube of a number
  program/find-cube-of-a-number/FindCubeOfANumber.cpp
Labels: C++

#304 [ 🚧 WIP ] issue #50 square number js complete
  program/find-square-of-a-number/FindSquareOfANumber.js
Labels: JavaScript

#305 [ 🚧 WIP ] Added JS program to convert meters to miles
  program/convert-meters-to-miles/ConvertMetersToMiles.js
Labels: JavaScript
