Repository codinasion/program, pull requests merged in 2022-12, with the labels that each got.

#4879 Create `find_square_of_a_number.php`
  program/find-square-of-a-number/find_square_of_a_number.php
Labels: triage

#4880 Create `find_volume_of_a_cube.php`
  program/find-volume-of-a-cube/find_volume_of_a_cube.php
Labels: triage

#4873 Create `find-the-adjoint-of-a-matrix.py`
  program/find-the-adjoint-of-a-matrix/find-the-adjoint-of-a-matrix.py
Labels: triage

#4883 :construction: feat: added Java# solution to find the adjoint of a matrix
  program/find-the-adjoint-of-a-matrix/find-the-adjoint-of-a-matrix.java
Labels: triage

#4885 Create `convert_meters_to_miles.php`
  program/convert-meters-to-miles/convert_meters_to_miles.php
Labels: triage

#4884 Create `find_volume_of_a_cuboid.php`
  program/find-volume-of-a-cuboid/find_volume_of_a_cuboid.php
Labels: triage

#4889 Create `convert_decimal_to_binary.php`
  program/convert-decimal-to-binary/convert_decimal_to_binary.php
Labels: triage

#4886 Create `convert_octal_to_hexadecimal.php`
  program/convert-octal-to-hexadecimal/convert_octal_to_hexadecimal.php
Labels: triage

#4890 Create `convert_hexadecimal_to_decimal.php`
  program/convert-hexadecimal-to-decimal/convert_hexadecimal_to_decimal.php
Labels: triage

#4887 Create `convert_octal_to_binary.php`
  program/convert-octal-to-binary/convert_octal_to_binary.php
Labels: triage

#4888 Create `convert_decimal_to_hexadecimal.php`
  program/convert-decimal-to-hexadecimal/convert_decimal_to_hexadecimal.php
Labels: triage

#4895 SwapTwoNumbersWithoutUsingThirdVariable
  program/swap-two-numbers-without-using-third-variable/SwapTwoNumbersWithoutUsingThirdVariable.kt
Labels: triage

#4894 convert days to week
  program/convert-days-to-weeks/convert-days-to-weeks.js
Labels: triage

#4896 Create `ConvertStringToCamelcase.js`
  program/convert-string-to-camelcase/ConvertStringToCamelcase.js
Labels: triage

#4898 Create `convert_binary_to_octal.php`
  program/convert-binary-to-octal/convert_binary_to_octal.php
Labels: triage

#4893 Create `find_factorial_of_a_number_by_recursion.php`. #3206.
  program/find-factorial-of-a-number-by-recursion/find_factorial_of_a_number_by_recursion.php
Labels: triage

#4892 Create `PrintDiamondPattern.js`
  program/print-diamond-pattern/PrintDiamondPattern.js
Labels: triage

#4904 Print Numbers from N to 1 without using loop
  program/print-numbers-from-n-to-1-without-using-a-loop/print_numbers_from_n_to_1_without_using_a_loop.php
Labels: triage

#4907 Lcm of two numbers recursion
  program/find-lcm-of-two-numbers-by-recursion/find_lcm_of_two_numbers_by_recursion.php
Labels: triage

#4905 Surface area cone
  program/find-surface-area-of-a-cone/FindSurfaceAreaOfACone.rb
Labels: triage

#4900 Program/print ascii value of a character
  program/print-ascii-value-of-a-character/PrintAsciiValueOfACharacter.kt
Labels: triage

#4903 TypeScript program to find average of numbers by recursion
  program/find-average-of-numbers-by-recursion/FindAverageOfNumbersByRecursion.ts
Labels: TypeScript

#5184 created ConvertStringToConsonantcase.cpp
  program/convert-string-to-consonantcase/ConvertStringToConsonantcase.cpp
Labels: triage

#5249 Add ConvertRupeesToPaise.ts
  program/convert-rupees-to-paise/ConvertRupeesToPaise.js
  program/convert-rupees-to-paise/ConvertRupeesToPaise.ts
Labels: triage

#5292 Add ConvertRupeesToPaise.c and ConvertRupeesToPaise.cpp
  program/convert-rupees-to-paise/ConvertRupeesToPaise.c
  program/convert-rupees-to-paise/ConvertRupeesToPaise.cpp
Labels: triage

#5314 Create FindSumOfSquaresOfNumbers.ts
  program/find-sum-of-squares-of-numbers/FindSumOfSquaresOfNumbers.ts
Labels: triage

#5315 [ 🚧 WIP ] Create CalculateSimpleInterest.java
  program/calculate-simple-interest/CalculateSimpleInterest.java
Labels: Java

#5185 Print numbers to words
  program/print-number-to-words-in-indian-numbering-system/PrintNumberToWordsInIndianNumberingSystem.js
Labels: triage

#5659 Added TypeScript Function to split an string into array of words
  program/split-string-into-array-of-words/SplitStringIntoArrayOfWords.ts
Labels: triage

#5660 finished program to split input string to an array of words
  program/split-string-into-array-of-words/split-string-into-array-of-words.py
Labels: triage

#5663 Create SplitStringIntoArrayOfWords.java
  program/split-string-into-array-of-words/SplitStringIntoArrayOfWords.java
Labels: triage

#5668 Reverse a number by recursion
  program/print-reverse-of-a-number-by-recursion/PrintReverseOfANumberByRecursion.js
Labels: triage

#5666 Split string into array
  program/split-string-into-array-of-words/split_string_into_array_of_words.php
Labels: triage

#5664 String to array
  program/split-string-into-array-of-words/SplitStringIntoArrayOfWords.js
Labels: triage

#5661 finished program to reverse an array in python
  program/reverse-an-array/reverse-an-array.py
Labels: triage

#5670 Convert inches to feet
  program/convert-inches-to-feet/ConvertInchesToFeet.ts
Labels: triage

#5667 Inches to feet
  program/convert-inches-to-feet/ConvertInchesToFeet.js
Labels: triage

#5669 ConvertFeetToInches.js
  program/convert-feet-to-inches/ConvertFeetToInches.js
Labels: triage

#5674 SplitStringIntoArrayOfWords.cpp
  program/split-string-into-array-of-words/SplitStringIntoArrayOfWords.cpp
Labels: triage

#5676 fixed issue #5533 in javascript / length of a string
  program/find-length-of-a-string/FindLenghtOfAString.js
Labels: triage

#5662 Update program/convert-rupees-to-paise
  program/convert-rupees-to-paise/ConvertRupeesToPaise.cs
  program/convert-rupees-to-paise/ConvertRupeesToPaise.dart
  program/convert-rupees-to-paise/ConvertRupeesToPaise.java
  program/convert-rupees-to-paise/ConvertRupeesToPaise.kt
  program/convert-rupees-to-paise/ConvertRupeesToPaise.php
  program/convert-rupees-to-paise/ConvertRupeesToPaise.pl
  program/convert-rupees-to-paise/ConvertRupeesToPaise.py
Labels: triage

#5679 added method to print numbers from 1 to n without using a loop
  program/print-numbers-from-1-to-n-without-using-a-loop/print-numbers-from-1-to-n-without-using-a-loop.py
Labels: triage

#5677 Split string into array
  program/split-string-into-array-of-words/SplitStringIntoArrayOfWords.rb
Labels: triage

#5673 Inches to feet
  program/convert-inches-to-feet/convert_inches_to_feet.php
Labels: triage

#5680 JavaScript program to print floyd's triangle
  program/print-floyd's-triangle/PrintFloydsTriangle.js
Labels: triage

#5687 [ 🚧 WIP ] Create split_string_into_array_of_words.rs
  program/split-string-into-array-of-words/split_string_into_array_of_words.rs
Labels: Rust

#5671 Create `convert-inches-to-feet.py`
  program/convert-inches-to-feet/convert-inches-to-feet.py
Labels: triage

#5681 Create `PrintNumbersFrom1ToN.java`
  program/print-numbers-from-1-to-n/PrintNumbersFrom1ToN.java
Labels: triage

#5683 Fix issue 5510 / weeksToDays
  program/convert-weeks-to-days/ConvertWeeksToDays.js
Labels: triage

#5684 FindSumOfDigitsOfANumber.js
  program/find-sum-of-digits-of-a-number/FindSumOfDigitsOfANumber.js
Labels: triage

#5685 Find length of a given string
  program/find-length-of-a-string/FindLengthOfAString.ts
Labels: triage

#5686 Convert given weeks to days
  program/convert-weeks-to-days/ConvertWeeksToDays.ts
Labels: triage

#5692 Create convert_inches_to_feet.rs
  program/convert-inches-to-feet/convert_inches_to_feet.rs
Labels: triage

#5691 Create MergeTwoStrings.java
  program/merge-two-strings/MergeTwoStrings.java
Labels: triage

#5690 Create FindLengthOfAString.java
  program/find-length-of-a-string/FindLengthOfAString.java
Labels: triage

#5693 Fixed issue #5259/ js program to find sum of squares of numbers
  program/find-sum-of-squares-of-numbers/FindSumOfSquaresOfNumbers.js
Labels: triage

#5531 Create `MergeTwoStrings.js`
  program/merge-two-strings/MergeTwoStrings.js
Labels: triage

#5695 Convert Fahrenheit to Celsius in Typescript
  program/convert-fahrenheit-to-celsius/ConvertFahrenheitToCelsius.ts
Labels: triage

#5696 Added function for printing elements of an array in TS
  program/print-elements-of-an-array/PrintElementsOfAnArray.ts
Labels: triage

#5697 Feet to inches
  program/convert-feet-to-inches/convert_feet_to_inches.php
Labels: triage

#5700 Convert Feet to inches
  program/convert-feet-to-inches/ConvertFeetToInches.java
Labels: triage

#5701 Convert weeks to days
  program/convert-weeks-to-days/ConvertWeeksToDays.java
Labels: triage

#5675 Reverse a number using recursion
  program/print-reverse-of-a-number-by-recursion/print_reverse_of_a_number_by_recursion.php
Labels: triage

#5705 Added a TypeScript function to merge two strings
  program/merge-two-strings/MergeTwoStrings.ts
Labels: triage

#5707 Find length string
  program/find-length-of-a-string/find-length-of-a-string.py
  program/find-sum-of-digits-of-a-number/find-sum-of-digits-of-a-number.py
Labels: triage

#5708 Floyds triangle
  program/print-floyd's-triangle/PrintFloyd'sTriangle.java
Labels: triage

#5702 Create `convert-feet-to-inches.py`
  program/convert-feet-to-inches/convert-feet-to-inches.py
Labels: triage

#5712 Reverse number using recursion in java
  program/print-reverse-of-a-number-by-recursion/PrintReverseOfANumberByRecursion.java
Labels: triage

#5713 implemented convert-weeks-to-days for python
  program/convert-weeks-to-days/convert-weeks-to-days.py
Labels: triage

#5716 Create `ReverseAnArray.java`
  program/reverse-an-array/ReverseAnArray.java
Labels: triage

#5715 Create `PrintNumbersFrom1ToNWithoutUsingALoop.java`
  program/print-numbers-from-n-to-1-without-using-a-loop/PrintNumbersFrom1ToNWithoutUsingALoop.java
Labels: triage

#5711 Find the average of all numbers in an array
  program/find-the-average-of-all-numbers-in-an-array/FindTheAverageOfAllNumbersInAnArray.ts
Labels: triage

#5717 Fix typo
  CONTRIBUTING.md
Labels: triage

#5718 Floyds triangle in PHP
  program/print-floyd's-triangle/print_floyd's_triangle.php
Labels: triage

#5719 Simple interest in PHP
  program/calculate-simple-interest/calculate_simple_interest.php
Labels: triage

#5710 Added a function to calculate the sum of first n natural numbers usin…
  program/find-sum-of-n-natural-numbers-using-formula/FindSumOfNNaturalNumbersUsingFormula.ts
Labels: triage

#5727 Create FindSumOfNNaturalNumbersUsingFormula.java
  program/find-sum-of-n-natural-numbers/FindSumOfNNaturalNumbersUsingFormula.java
Labels: triage

#5726 Create FindSumOfDigitsOfANumber.java
  program/find-sum-of-digits-of-a-number/FindSumOfDigitsOfANumber.java
Labels: triage

#5725 Create FindTheAverageOfAllNumbersInAnArray.java
  program/find-the-average-of-all-numbers-in-an-array/FindTheAverageOfAllNumbersInAnArray.java
Labels: triage

#5724 Create FindAverageOfDigitsOfANumberByRecursion.java
  program/find-average-of-numbers-by-recursion/FindAverageOfDigitsOfANumberByRecursion.java
Labels: triage

#5723 Create PrintElementsOfAnArray.java
  program/print-elements-of-an-array/PrintElementsOfAnArray.java
Labels: triage

#5721 Fibonacci series by recursion
  program/print-fibonacci-series-by-recursion/print_fibonacci_series_by_recursion.php
Labels: triage

#5730 Change `float` to `double` in `ConvertRupeesToPaise.dart`
  program/convert-rupees-to-paise/ConvertRupeesToPaise.dart
Labels: triage

#5722 Create `ConvertFeetToInches.rb`
  program/convert-feet-to-inches/ConvertFeetToInches.rb
Labels: triage

#5732 Fixed issue #5048 // python program to print surface area of a cylinder
  program/find-surface-area-of-a-cylinder/find-surface-area-of-a-cylinder.py
Labels: triage

#5729 [ 🚧 WIP ] added split_string_into_array_of_words.dart
  program/split-string-into-array-of-words/split_string_into_array_of_words.dart
Labels: Dart

#5728 Haskell solution: splitting string into char array
  program/split-string-into-array-of-characters/split_string_into_array_of_characters.hs
Labels: triage

#5733 Fixed issue #5501 // python program to print floyd's triangle
  program/print-elements-of-an-array/print-elements-of-an-array.py
  program/print-floyd's-triangle/print-floyd's-triangle.py
Labels: triage

#5734 improve footer
  website/src/components/Footer/FooterText.tsx
Labels: website

#5698 [ 🚧 WIP ] finished working the rotate matrix challenge
  program/cylindrically-rotate-a-matrix-by-90-degrees/rotateMatrix.js
Labels: JavaScript

#5678 [ 🚧 WIP ] added program of print numbers from 1 to n
  program/print-numbers-from-1-to-n/PrintNumbersFrom1ToN.js
Labels: JavaScript

#5688 [ 🚧 WIP ] create print-reverse-of-a-number-by-recursion.py
  program/print-reverse-of-a-number-by-recursion/print-reverse-of-a-number-by-recursion.py
Labels: Python

#5738 Convert inches to feet in Dart
  program/convert-inches-to-feet/convert_inches_to_feet.dart
Labels: triage

#5739 convert_feet_to_inches in Dart
  program/convert-feet-to-inches/convert_feet_to_inches.dart
Labels: triage

#5740 [ 🚧 WIP ] Fixed issue #5437 #5351 // python program to merge two strings //python program to find sum of n natural by formula
  program/find-sum-of-n-natural-numbers-using-formula/find-sum-of-n-natural-numbers-using-formula.py
  program/find-sum-of-squares-of-numbers/find-sum-of-squares-of-numbers.py
  program/merge-two-strings/merge-two-strings.py
Labels: Python

#5743 Create `print_elements_of_an_array.dart`
  program/print-elements-of-an-array/print_elements_of_an_array.dart
Labels: triage

#5745 create PrintReverseOfANumberByRecursion.rb
  program/print-reverse-of-a-number-by-recursion/PrintReverseOfANumberByRecursion.rb
Labels: triage

#5746 filter program by lang done instant
  website/pages/index.tsx
Labels: triage

#5737 [ 🚧 WIP ] codes (py, js, ts) to Calculate simple interest
  program/calculate-simple-interest/CalculateSimpleInterest.js
  program/calculate-simple-interest/CalculateSimpleInterest.py
  program/calculate-simple-interest/CalculateSimpleInterest.ts
  program/calculate-simple-interest/README.md
Labels: JavaScript, Python, TypeScript

#5741 Create `find-the-eigenvalues-of-a-matrix.py`
  program/find-the-eigenvalues-of-a-matrix/find-the-eigenvalues-of-a-matrix.py
Labels: triage

#5744 chore: Add JavaScript program to convert fahrenheit to celsius
  program/convert-fahrenheit-to-celsius/ConvertFahrenheitToCelcius.js
Labels: triage

#5749 Add convertStringToReverseCase function.
  program/convert-string-to-reversecase/ConvertStringToReversecase.js
Labels: triage

#5742 Find length of a string in Dart
  program/find-length-of-a-string/find_length_of_a_string.dart
Labels: triage

#5750 create ConvertWeeksToDays.rb
  program/convert-weeks-to-days/ConvertWeeksToDays.rb
Labels: triage

#5748 Create `FindPowerOfANumber.java` and `FindSurfaceAreaOfACylinder.java`
  program/find-power-of-a-number/FindPowerOfANumber.java
  program/find-surface-area-of-a-cylinder/FindSurfaceAreaOfACylinder.java
Labels: triage

#5752 create FindLengthOfAString.rb
  program/find-length-of-a-string/FindLengthOfAString.rb
Labels: triage

#5754 Create `convert-string-to-sentencecase.py`
  program/convert-string-to-sentencecase/convert-string-to-sentencecase.py
Labels: triage

#5755 Create `print_multiplication_table.php`
  program/print-multiplication-table/print_multiplication_table.php
Labels: triage

#5759 Rotate a matrix by 90 degrees
  program/cylindrically-rotate-a-matrix-by-90-degrees/cylindrically-rotate-a-matrix-by-90-degrees.py
Labels: triage

#5758 Week to days conversion
  program/convert-weeks-to-days/convert_weeks_to_days.php
Labels: triage

#5762 Flyod's Triangle in TS
  program/print-floyd's-triangle/PrintFloyd'sTriangle.ts
Labels: triage

#5769 Length of string
  program/find-length-of-a-string/find_length_of_a_string.php
Labels: triage

#5751 Feature/print reverse of a number
  program/convert-miles-to-meters/ConvertMilesToMeters.kt
  program/convert-minutes-to-hours/ConvertMinutesToHours.kt
  program/print-reverse-of-a-number/PrintReverseOfANumber.kt
Labels: triage

#5756 Feature/convert string to camelcase
  program/convert-string-to-camelcase/ConvertStringToCamelcase.kt
Labels: triage

#5757 Feature/check leap year
  program/check-leap-year/CheckLeapYear.kt
Labels: triage

#5764 Feature/find average of digits of a number
  program/find-average-of-digits-of-a-number/FindAverageOfDigitsOfANumber.kt
Labels: triage

#5765 Feature/find factorial of a number
  program/find-factorial-of-a-number/FindFactorialOfANumber.kt
Labels: triage

#5766 Feature/convert miles to inches
  program/convert-miles-to-inches/ConvertMilesToInches.kt
Labels: triage

#5767 Feature/convert feet to centimeters
  program/convert-feet-to-centimeters/ConvertFeetToCentimeters.kt
Labels: triage

#5768 feat: add Javascript program to find sum of n natural numbers
  program/find-sum-of-n-natural-numbers-using-formula/FindSumOfNNaturalNumbersUsingFormula.js
Labels: triage

#5770 Merge strings
  program/merge-two-strings/merge_two_strings.php
Labels: triage

#5774 Merge strings
  program/merge-two-strings/MergeTwoStrings.rb
Labels: triage

#5775 Create `PrintElementsOfAnArray.rb`
  program/print-elements-of-an-array/PrintElementsOfAnArray.rb
Labels: triage

#5771 Create `find_length_of_a_string.pl`
  program/find-length-of-a-string/find_length_of_a_string.pl
Labels: triage

#5776 C : convert feet into inches
  program/convert-feet-to-inches/convert_feet_into_inches.c
Labels: triage

#5773 Haskell solution: convert feet to inches
  program/convert-feet-to-inches/convert_feet_to_inches.hs
Labels: triage

#5772 Haskell solution: convert_inches_to_feet
  program/convert-inches-to-feet/convert_inches_to_feet.hs
Labels: triage

#5777 add ConvertStringToAlternatingcase.rb
  program/convert-string-to-alternatingcase/ConvertStringToAlternatingcase.rb
Labels: triage

#5763 Cylindrically Rotate 90 degrees
  program/cylindrically-rotate-a-matrix-by-90-degrees/CylindricallyRotateAMatrixBy90Degrees.ts
Labels: triage

#5779 add ConvertStringToReversecase.rb
  program/convert-string-to-reversecase/ConvertStringToReversecase.rb
Labels: triage

#5790 Create `convert_weeks_to_days.rs`
  program/convert-weeks-to-days/convert_weeks_to_days.rs
Labels: triage

#5789 Create `FindSumOfSquaresOfNumbers.rb`
  program/find-sum-of-squares-of-numbers/FindSumOfSquaresOfNumbers.rb
Labels: triage

#5788 Create `merge_two_strings.pl`
  program/merge-two-strings/merge_two_strings.pl
Labels: triage

#5782 Feature/convert string to uppercase
  program/convert-octal-to-binary/ConvertOctalToBinary.kts
  program/convert-string-to-uppercase/ConvertStringToUppercase.kt
Labels: triage

#5783 Feature/check valid date
  program/check-valid-date/CheckValidDate.kt
Labels: triage

#5784 Feature/convert seconds to weeks
  program/convert-seconds-to-weeks/ConvertSecondsToWeeks.kt
Labels: triage

#5780 Feature/check digit
  program/check-digit/CheckDigit.kt
Labels: triage

#5786 Inches to feet in perl
  program/convert-inches-to-feet/convert_inches_to_feet.pl
Labels: triage

#5792 ConvertInchesToFeet.cpp
  program/convert-inches-to-feet/ConvertInchesToFeet.cpp
Labels: triage

#5793 PrintReverseOfANumberByRecursion.cpp
  program/print-reverse-of-a-number-by-recursion/PrintReverseOfANumberByRecursion.cpp
Labels: triage

#5785 Split string into array in perl
  program/split-string-into-array-of-words/split_string_into_array_of_words.pl
Labels: triage

#5796 Convert String to Alternate case
  program/convert-string-to-alternatingcase/ConvertStringToAlternatingcase.js
Labels: triage

#5798 print reverse of a number by recursion TS
  program/print-reverse-of-a-number-by-recursion/PrintReverseOfANumberByRecursion.ts
Labels: triage

#5801 Solved #5536
  program/find-length-of-a-string/string_length.cpp
Labels: triage

#5802 Added convert feet to inches cpp
  program/convert-feet-to-inches/convert_feet_to_inches.cpp
Labels: triage

#5787 Feet to inches in perl
  program/convert-feet-to-inches/convert_feet_to_inches.pl
Labels: triage

#5794 Sum of digits of a number
  program/find-sum-of-digits-of-a-number/find_sum_of_digits_of_a_number.php
Labels: triage

#5795 Sum of 'n' natural numbers
  program/find-sum-of-n-natural-numbers-using-formula/find_sum_of_n_natural_numbers_using_formula.php
Labels: triage

#5797 Calculate simple interest
  program/calculate-simple-interest/CalculateSimpleInterest.rb
Labels: triage

#5800 Convert String to Reversecase
  program/convert-string-to-reversecase/convert_string_to_reversecase.php
Labels: triage
